# Generated by Django 5.1.2 on 2025-04-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_review_unique_together_and_more'),
        ('products', '0007_alter_review_unique_together_product_user_and_more'),
    ]

    operations = [
    ]
